lolApiKey : RGAPI-3158d4c4-f286-4800-bab4-9fb54e14d6c4
baseUrl : https://kr.api.pvp.net
fbAccessToken : EAABop5GmlVkBALTnYZAfuMWXeOtDlcdSVDVFSZCyWbC6oPirsEVGYlnhimUAeD4emFF12SgQ90pqQy8ac8OM2lpyt5JwvwiA0ZAZCzl4yucABTZBZAX7leNRjeSu42hOBfLZChGrG62RlhSf5T6UWNrA1DLLHI5Ar6GI7EGXe75EgZDZD
exchangeNumber : +82
fbUrl : https://graph.facebook.com/v2.6/

logging:
  config: classpath:logback.xml
  
spring:
  application:
    name: "@pom.artifactId@"

info:
  application-group-id: "@pom.groupId@"
  application-artifact-id: "@pom.artifactId@"
  application-version: "@pom.version@"
---

spring:
  profiles: production
 
logging:
  config: classpath:logback-production.xml