baseUrl : https://kr.api.riotgames.com/
fbAccessToken : EAAHLpxwzM0MBADkd6os5yWFqSpzBTOdcX1lZAZAWMV0bBVMHFeddsec4c4ZAnbCdmWWOBiAQhicVm58Eukg6qdtE7nsbmj7diARe4dDmvZBfwcmWpxxYyYlfRHpEN3TWyW9LWAY6pr7B1GiOpOFJiTxYxoPgX5EpaDjRKQlfi37raUNWfEXx
exchangeNumber : +82
fbUrl : https://graph.facebook.com/v2.6/

logging:
  config: classpath:logback.xml
  
spring:
  application:
    name: "@pom.artifactId@"
  jpa:
   generate-ddl: false
   show-sql: false
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/lolhuni
    username: lolhuni
    password: cola12#$
   
info:
  application-group-id: "@pom.groupId@"
  application-artifact-id: "@pom.artifactId@"
  application-version: "@pom.version@"
---

spring:
  profiles: production
  datasource:
    driverClassName: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://13.124.165.240:3306/lolhuni?autoReconnect=true
    username: lolhuni
    password: allmeat12#$
    tomcat:
     initial-size: 10
     max-active: 20
     min-idle: 10
     max-idle: 10
     max-wait: 3000
logging:
  config: classpath:logback-production.xml