lolApiKey : RGAPI-1a23209f-046d-499f-b01b-b3170d0c820b
baseUrl : https://kr.api.riotgames.com/
fbAccessToken : EAAHLpxwzM0MBADkd6os5yWFqSpzBTOdcX1lZAZAWMV0bBVMHFeddsec4c4ZAnbCdmWWOBiAQhicVm58Eukg6qdtE7nsbmj7diARe4dDmvZBfwcmWpxxYyYlfRHpEN3TWyW9LWAY6pr7B1GiOpOFJiTxYxoPgX5EpaDjRKQlfi37raUNWfEXx
exchangeNumber : +82
fbUrl : https://graph.facebook.com/v2.6/

logging:
  config: classpath:logback.xml
  
spring:
  application:
    name: "@pom.artifactId@"

info:
  application-group-id: "@pom.groupId@"
  application-artifact-id: "@pom.artifactId@"
  application-version: "@pom.version@"
---

spring:
  profiles: production
 
logging:
  config: classpath:logback-production.xml