package com.hj.lolhuni.model.lol;

import lombok.Getter;
import lombok.Setter;
import lombok.ToString;

@Getter
@Setter
@ToString
public class RawStatsDto {
	
	private int gold;
	private int magicDamageDealtToChampions;
	private int largestMultiKill;
	private int totalDamageDealtToBuildings;
	private int teamObjective;
	private int trueDamageDealtPlayer;
	private int tripleKills;
	private int nodeNeutralizeAssist;
	private int playerScore9;
	private int playerScore8;
	private int playerScore1;
	private int playerScore0;
	private int playerScore3;
	private int playerScore2;
	private int playerScore5;
	private int playerScore4;
	private int playerScore7;
	private int playerScore6;
	private int totalScoreRank;
	private int neutralMinionsKilled;
	private int playerRole;
	private int physicalDamageDealtToChampions;
	private int level;
	private int numItemsBought; 
	private int nodeCapture;
	private int turretsKilled;
	private int totalUnitsHealed;
	private int team;
	private int totalDamageTaken;
	private int victoryPointTotal;
	private int visionWardsBought;
	private int largestCriticalStrike;
	private int firstBlood;
	private int largestKillingSpree;
	private int quadraKills;
	private int magicDamageTaken;
	private int item2;
	private int item3;
	private int item0;
	private int item1;
	private int item6;
	private int item4;
	private int item5;
	private int neutralMinionsKilledYourJungle;
	private int timePlayed; 
	private boolean nexusKilled;
	private int trueDamageTaken;
	private int nodeNeutralize;
	private int damageDealtPlayer;
	private int assists;
	private int spell1Cast;
	private int goldSpent;
	private int totalTimeCrowdControlDealt;
	private int minionsDenied;
	private int totalDamageDealtToChampions;
	private int spell3Cast;
	private int physicalDamageTaken;
	private int totalPlayerScore;
	private boolean win;
	private int objectivePlayerScore;
	private int totalDamageDealt;
	private int playerPosition;
	private int spell4Cast;
	private int bountyLevel;
	private int neutralMinionsKilledEnemyJungle;
	private int spell2Cast;
	private int sightWardsBought;
	private int championsKilled;
	private int trueDamageDealtToChampions;
	private int summonSpell1Cast;
	private int physicalDamageDealtPlayer;
	private int goldEarned;
	private int superMonsterKilled;
	private int killingSprees;
	private int unrealKills;
	private int wardPlaced;
	private int barracksKilled;
	private int wardKilled;
	private int consumablesPurchased;
	private int legendaryItemsCreated;
	private int minionsKilled;
	private int itemsPurchased;
	private int doubleKills;
	private int nodeCaptureAssist;
	private int summonSpell2Cast;
	private int combatPlayerScore;
	private int pentaKills;
	private int totalHeal;
	private int numDeaths;
	private int magicDamageDealtPlayer;
	private int totalDamageSelfMitigated;
	private int totalDamageDealtToObjectives;
	private int totalDamageDealtToTurrets;
	private int visionScore;
	private int timeCCingOthers;
	
}
